[package]
name = "gh-user-summary"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
fern = "0.7.1"
log = "0.4.27"
colored = "3.0.0"
serde_json = "1.0.140"
