name: On Version Tagged, Build and Publish Rust Binaries
on:
  push:
    tags:
    - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    uses: harmony-labs/workflow-rust-release/.github/workflows/workflow.yaml@v2.0.2
    with:
      executable_name: ${{ github.event.repository.name }}